### PR TITLE
Test3

### PR DESCRIPTION
**Pull request by karussell**
Now you can try squashing & merging

### CODE REVIEW

**Comment by boldtrn** [comment]
Using the UI button?

**Comment by karussell** [comment]
yes "squash and merge"

**Comment by boldtrn** [comment]
Similar to #1. If the contributor squashes the PR themself it's verified if someone else squashes the PR it is not verified.

**Comment by boldtrn** [comment]
Also see this commit: https://github.com/boldtrn/test-github/commit/89969d6fd9b610913de451c93d8fc2471e83dabe

**Comment by karussell** [comment]
Strange, I asked this to the github support.

**Comment by karussell** [comment]
Got the answer:

> It is currently expected behaviour for squashed commits not to show the verified badge.
> 
> The reason for this is the committer is currently set to the user who merged the commit. This means we cannot set the committer email to our GitHub verifiable email to sign those commits.
> 
> We've passed your feedback onto the team to consider for future improvements though. I can't promise if or when we'd change the current behaviour but you're feedback is with the team.

**Comment by boldtrn** [comment]
Thanks for asking. I thought that it might be something like this.

**Pull request merged**
