### PR TITLE
start over

### PR DESCRIPTION
**Pull request by karussell**

### CODE REVIEW

**Comment by karussell** [comment]
@boldtrn Would you mind to allow me access to this repo? Maybe if I do the squashing this is ok.

**Comment by boldtrn** [comment]
I added you as a contributor.

**Comment by karussell** [comment]
I cannot merge it somehow. Can you try once again? I contacted the author of this elasticsearch commit and she said she didn't do anything to make it signed. Also I've read through:

https://help.github.com/articles/about-gpg/

and it seems they use a "web-flow" gpg key for everyone so it can work without anything to set up. Also my recent commit via github UI is signed:

https://github.com/karussell/graphhopper-traffic-data-integration/commit/3e23b13c2ee44a050bf24fea5661c6aa69ff61c2

**Comment by karussell** [comment]
Ups, had to accept the invitation first ... will now squash merge and open a new one so that you can test it too again

**Comment by karussell** [comment]
Yeah, it is signed!

**Pull request merged**
